version: "3.9"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/cpp:1-debian-12
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      - DOCKER_BUILDKIT=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - host.docker.internal:host-gateway
